[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = {version = "1.0.4", features = ["alloc"]}
serde = { version = "1.0.148", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
