[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1", features = ["full"] }
